# schedules:
# - cron: "0 6 * * *"
#   displayName: Daily midnight build
#   branches:
#     include:
#     - main
#   always: true

trigger:
  tags:
    include:
    - '*testing'
  branches:
    exclude:
    - main

name: $(Date:yyyyMMdd)$(Rev:.r)

jobs:
- job: linux
  timeoutInMinutes: 120
  pool: {vmImage: 'Ubuntu-latest'}
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'
      Python310:
        python.version: '3.10'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel==2.9.0
      displayName: Install dependencies
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
    # - task: PublishBuildArtifacts@1
    #   inputs: {pathtoPublish: 'wheelhouse'}
    - script: python -m pip install --upgrade twine
      displayName: 'Install Twine'
    - task: TwineAuthenticate@1
      inputs:
        pythonUploadServiceConnection: pypitest
    - script: cat $(PYPIRC_PATH)
    - script: python -m twine upload --skip-existing --non-interactive -u $(TWINE_USERNAME) -p $(TWINE_PASSWORD)--verbose --repository-url https://test.pypi.org/legacy/ --config-file $(PYPIRC_PATH) wheelhouse/*
      displayName: 'Publish to PyPi through Twine'

# -r esi-core -repository-url https://test.pypi.org/legacy/

- job: macos
  timeoutInMinutes: 120
  pool: {vmImage: 'macOS-latest'}
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'
      Python310:
        python.version: '3.10'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        python3 -m pip install cibuildwheel==2.9.0
      displayName: Install dependencies
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: wheelhouse}

- job: windows
  timeoutInMinutes: 120
  pool: {vmImage: 'windows-latest'}
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'
      Python310:
        python.version: '3.10'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
    - bash: |
        set -o errexit
        python -m pip install --upgrade pip
        pip install cibuildwheel==2.9.0
      displayName: Install dependencies
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}